modLoader = "javafml"
loaderVersion = "${loader_range}"
issueTrackerURL = "https://github.com/justduck25/Continuum-Mantle/issues"
logoFile = "Mantle.png"
license = "MIT"

[[mods]]
modId = "mantle"
version = "${version}"
displayName = "Continuum Core"
authors = "Slime Knights, justduck25"
description = '''
Shared library code for the NeoForge 26.1 Continuum Construct port.
'''
displayURL = "https://github.com/justduck25/Continuum-Mantle"

[[dependencies.mantle]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.mantle]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_range}"
ordering = "NONE"
side = "BOTH"
